#!/usr/bin/python3
import os
import json
import threading
import time
import configparser
from ytmusicapi import YTMusic
from yt_dlp import YoutubeDL
from flask import Flask, render_template, request, url_for, flash, redirect, session, make_response

config = configparser.ConfigParser()
config.read("config.ini")
HOST = config["config"]["host"]
PORT = config["config"]["port"]
DEFAULTSTYLESHEET = config["config"]["defaultstylesheet"]

print("🎉 Burgertunes server started!")

app = Flask(__name__)

audioformat = "mp4"
ydl_opts = {"format": "best[ext=mp4]",
            "noplaylist": "True",
            "outtmpl": "static/cache/%(id)s." + audioformat}

# ydl_opts = {"format": "bestaudio", "noplaylist": "True",
#            "outtmpl": "static/cache/%(id)s.%(ext)s"}

def SearchMusic(query, searchtype, limit):
    ytmusic = YTMusic()
    search_results = ytmusic.search(
        query, searchtype, None, limit, ignore_spelling=False)
    return search_results


def GetChannel(id):
    ytmusic = YTMusic()
    data = ytmusic.get_artist(id)
    return data


def GetAlbum(id):
    ytmusic = YTMusic()
    data = ytmusic.get_album(id)
    return data

def DeleteDir(dir):
    if dir[-1] == os.sep: dir = dir[:-1]
    files = os.listdir(dir)
    for file in files:
        if file == '.' or file == '..': continue
        path = dir + os.sep + file
        if os.path.isdir(path):
            nukedir(path)
        else:
            os.unlink(path)
    os.rmdir(dir)

def ResetCache():
    DeleteDir("static/cache")
    os.mkdir("static/cache")


def GetTheme():
    if "style" in request.cookies:
        style = request.cookies.get("style")
        style = "/static/css/" + style
    else:
        style = "/static/css/" + DEFAULTSTYLESHEET
    return style


@app.route("/", methods=("GET", "POST"))
def home():
    if request.method == "POST":
        searchkeyword = request.form["searchbar"]

        songresults = SearchMusic(searchkeyword, "songs", 40)
        albumresults = SearchMusic(searchkeyword, "albums", 10)
        return render_template("main.html", style=GetTheme(), results=songresults, albumresults=albumresults, searchkeyword=searchkeyword)

    songresults = SearchMusic("music", "songs", 40)
    albumresults = SearchMusic("music", "albums", 10)

    return render_template("main.html", style=GetTheme(), results=songresults, albumresults=albumresults, startPage=True)


@app.route('/music/<id>')
def music(id, methods=("GET", "POST")):
    with YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(id, download=False)

        imageurl = info["thumbnail"]
        channelid = info["channel_id"]
        audiourl = "/api/music/" + info["id"]
        title = info["title"]
        artistname = info["creator"]

        results = GetChannel(channelid)

        return render_template("player.html", style=GetTheme(), audiourl=audiourl, info=info, results=results)


@app.route('/api/music/<id>')
def apimusic(id, methods=("GET", "POST")):
    ResetCache()
    with YoutubeDL(ydl_opts) as ydl:
        ytfile = download = ydl.download(id)
        info = ydl.extract_info(id, download=False)

        return redirect("/static/cache/" + id + "." + audioformat)


@app.route('/api/album/<id>/<number>')
def apialbum(id, number, methods=("GET", "POST")):
    results = GetAlbum(id)
    songresult = results["tracks"][int(number)]

    ResetCache()

    with YoutubeDL(ydl_opts) as ydl:
        ytfile = download = ydl.download(songresult["videoId"])
        audiocontent = "/static/cache/" + \
            songresult["videoId"] + "." + audioformat

    return redirect(audiocontent)


@app.route('/album/<id>')
def album(id, methods=("GET", "POST")):
    results = GetAlbum(id)
    return render_template("albumview.html", style=GetTheme(), results=results, albumid=id)


@app.route('/artist/<id>')
def artist(id, methods=("GET", "POST")):
    info = GetChannel(id)
    return render_template("artist.html",  style=GetTheme(), info=info)


@app.route('/style/<stylesheet>')
def style(stylesheet, methods=("GET", "POST")):
    print(stylesheet)
    resp = make_response(redirect("/"))
    resp.set_cookie("style", stylesheet)
    return resp


@app.errorhandler(404)
def page_not_found(e):
    return render_template("error404.html", style=GetTheme())


@app.errorhandler(500)
def page_not_found(e):
    return render_template("error500.html", style=GetTheme())


if __name__ == "__main__":
    from waitress import serve
    serve(app, host=HOST, port=PORT)
    print("🔴 Burgertunes server stopped")
